### ISSUE TITLE
Issue when converting RTF from clipboard to HTML

### ISSUE THREAD

**Issue by DumboJet** [tbluemel/rtf.js#27] opened 2018-01-12 12:59 UTC
I have an issue when converting RTF from clipboard to HTML.
It tries to get a property of undefined:

![image](https://user-images.githubusercontent.com/8492662/34875933-08e09b38-f7a8-11e7-97be-f5020d4c46de.png)

It seems that the character is not found in the code page or something.
This is the RTF that I paste (The source PDF file from where I copy the data is attached [here](https://github.com/tbluemel/rtf.js/files/1626026/Test.RTF.data.pdf) - I use Acrobat Reader DC to open and copy the data):

```
{\rtf1\ansi\ansicpg1253\uc1 {\fonttbl\f0\fswiss\fcharset0 Calibri;\f1\fswiss\fcharset0 Calibri,Bold;\f2\fswiss\fcharset0 Calibri,Italic;\f3\fswiss\fcharset0 Calibri,BoldItalic;\f4\fnil\fcharset136 \'53\'79\'6D\'62\'6F\'6C;}\pard\plain\ql\f0\fs20 {\fs22 Test }{\b\f1\fs22 123 }{\fs22 Test 123 Test }{\i\f2\fs22 123 }{\fs22 Test }{\b\i\f3\fs22 123 }{\fs22 Test 123 Test 123\par }{\f4\fs22 {\uc2\u61623 \'84\'68}\'20}{\fs22 A\par }{\f4\fs22 {\uc2\u61623 \'84\'68}\'20}{\fs22 B\par }{\f4\fs22 {\uc2\u61623 \'84\'68}\'20}{\fs22 C}}
```

...and I use this code:

```
                                    var rtf = clipboardData.getData('text/rtf');

                                    var stringToBinaryArray = function(txt) {
                                        var buffer = new ArrayBuffer(txt.length);
                                        var bufferView = new Uint8Array(buffer);
                                        for (var i = 0; i < txt.length; i++) {
                                            bufferView[i] = txt.charCodeAt(i);
                                        }
                                        return buffer;
                                    }
                                    
                                    var settings = {};
                                    var doc = new window.RTFJS.Document(stringToBinaryArray(rtf), settings);
                                    var parts = doc.render();
                                    var pastedHtml = $('<div/>').append(parts).html();
```

Any ideas?
I use the full code page file (cptable.full.js), so it is weird...
Probably it should render a ? character when the code-page symbol is not found tough, right? :^)

**Comment by zoehneto** [comment] 2018-01-12 15:50
The issue is not with your code but with the rtf you're using. It uses codepage 950 for the symbol font which actually contains chinese characters not symbols. I've just committed a fix which ignores any characters it can't find a mapping for, we handle symbol fonts differently anyway.

**Closed by zoehneto** 2018-01-12 15:50 UTC
